//================================================================================
//  FileName: TeaClientServicePoxy.cs
//  Desc:
//
//  Called by
//
//  Auth:杨勇（jeason1914@gmail.com）
//  Date: 2013-10-12
//================================================================================
//  Change History
//================================================================================
//  Date  Author  Description
//  ----    ------  -----------------
//
//================================================================================
//  Copyright (C) 2004-2009 Jeason Young Corporation
//================================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.3038。
// 
namespace Yaesoft.SFIT.Client.TeaHost.Poxy.Impl
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "教师机客户端通信服务。Soap", Namespace = "http://ipower.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StudentWork))]
    public partial class TeaClientServicePoxy : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private CredentialSoapHeader credentialSoapHeaderValueField;

        private System.Threading.SendOrPostCallback VerifyUserIdentityOperationCompleted;

        private System.Threading.SendOrPostCallback DownloadTeaSyncDataOperationCompleted;

        private System.Threading.SendOrPostCallback UploadStudentWorksOperationCompleted;

        /// <remarks/>
        public TeaClientServicePoxy()
        {
            this.Url = "http://sfit.yaesoft.net/TeaClientService.asmx";
        }

        public CredentialSoapHeader CredentialSoapHeaderValue
        {
            get
            {
                return this.credentialSoapHeaderValueField;
            }
            set
            {
                this.credentialSoapHeaderValueField = value;
            }
        }

        /// <remarks/>
        public event VerifyUserIdentityCompletedEventHandler VerifyUserIdentityCompleted;

        /// <remarks/>
        public event DownloadTeaSyncDataCompletedEventHandler DownloadTeaSyncDataCompleted;

        /// <remarks/>
        public event UploadStudentWorksCompletedEventHandler UploadStudentWorksCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipower.org/VerifyUserIdentity", RequestNamespace = "http://ipower.org/", ResponseNamespace = "http://ipower.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CallResult VerifyUserIdentity(int type, string account, string password)
        {
            object[] results = this.Invoke("VerifyUserIdentity", new object[] {
                    type,
                    account,
                    password});
            return ((CallResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginVerifyUserIdentity(int type, string account, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("VerifyUserIdentity", new object[] {
                    type,
                    account,
                    password}, callback, asyncState);
        }

        /// <remarks/>
        public CallResult EndVerifyUserIdentity(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CallResult)(results[0]));
        }

        /// <remarks/>
        public void VerifyUserIdentityAsync(int type, string account, string password)
        {
            this.VerifyUserIdentityAsync(type, account, password, null);
        }

        /// <remarks/>
        public void VerifyUserIdentityAsync(int type, string account, string password, object userState)
        {
            if ((this.VerifyUserIdentityOperationCompleted == null))
            {
                this.VerifyUserIdentityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyUserIdentityOperationCompleted);
            }
            this.InvokeAsync("VerifyUserIdentity", new object[] {
                    type,
                    account,
                    password}, this.VerifyUserIdentityOperationCompleted, userState);
        }

        private void OnVerifyUserIdentityOperationCompleted(object arg)
        {
            if ((this.VerifyUserIdentityCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyUserIdentityCompleted(this, new VerifyUserIdentityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipower.org/DownloadTeaSyncData", RequestNamespace = "http://ipower.org/", ResponseNamespace = "http://ipower.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GeneralCallResultOfTeaSyncData DownloadTeaSyncData(string teacherID)
        {
            object[] results = this.Invoke("DownloadTeaSyncData", new object[] {
                    teacherID});
            return ((GeneralCallResultOfTeaSyncData)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDownloadTeaSyncData(string teacherID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DownloadTeaSyncData", new object[] {
                    teacherID}, callback, asyncState);
        }

        /// <remarks/>
        public GeneralCallResultOfTeaSyncData EndDownloadTeaSyncData(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((GeneralCallResultOfTeaSyncData)(results[0]));
        }

        /// <remarks/>
        public void DownloadTeaSyncDataAsync(string teacherID)
        {
            this.DownloadTeaSyncDataAsync(teacherID, null);
        }

        /// <remarks/>
        public void DownloadTeaSyncDataAsync(string teacherID, object userState)
        {
            if ((this.DownloadTeaSyncDataOperationCompleted == null))
            {
                this.DownloadTeaSyncDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadTeaSyncDataOperationCompleted);
            }
            this.InvokeAsync("DownloadTeaSyncData", new object[] {
                    teacherID}, this.DownloadTeaSyncDataOperationCompleted, userState);
        }

        private void OnDownloadTeaSyncDataOperationCompleted(object arg)
        {
            if ((this.DownloadTeaSyncDataCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadTeaSyncDataCompleted(this, new DownloadTeaSyncDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipower.org/UploadStudentWorks", RequestNamespace = "http://ipower.org/", ResponseNamespace = "http://ipower.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CallResult UploadStudentWorks(StudentWorkTeaUpload data)
        {
            object[] results = this.Invoke("UploadStudentWorks", new object[] {
                    data});
            return ((CallResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUploadStudentWorks(StudentWorkTeaUpload data, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UploadStudentWorks", new object[] {
                    data}, callback, asyncState);
        }

        /// <remarks/>
        public CallResult EndUploadStudentWorks(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CallResult)(results[0]));
        }

        /// <remarks/>
        public void UploadStudentWorksAsync(StudentWorkTeaUpload data)
        {
            this.UploadStudentWorksAsync(data, null);
        }

        /// <remarks/>
        public void UploadStudentWorksAsync(StudentWorkTeaUpload data, object userState)
        {
            if ((this.UploadStudentWorksOperationCompleted == null))
            {
                this.UploadStudentWorksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadStudentWorksOperationCompleted);
            }
            this.InvokeAsync("UploadStudentWorks", new object[] {
                    data}, this.UploadStudentWorksOperationCompleted, userState);
        }

        private void OnUploadStudentWorksOperationCompleted(object arg)
        {
            if ((this.UploadStudentWorksCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadStudentWorksCompleted(this, new UploadStudentWorksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ipower.org/", IsNullable = false)]
    public partial class CredentialSoapHeader : System.Web.Services.Protocols.SoapHeader
    {

        private string schoolIDField;

        private string accessAccountField;

        private string accessPasswordField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string SchoolID
        {
            get
            {
                return this.schoolIDField;
            }
            set
            {
                this.schoolIDField = value;
            }
        }

        /// <remarks/>
        public string AccessAccount
        {
            get
            {
                return this.accessAccountField;
            }
            set
            {
                this.accessAccountField = value;
            }
        }

        /// <remarks/>
        public string AccessPassword
        {
            get
            {
                return this.accessPasswordField;
            }
            set
            {
                this.accessPasswordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class TeacherReview
    {

        private string teacherIDField;

        private string teacherNameField;

        private EnumEvaluateType evaluateTypeField;

        private string reviewValueField;

        private string subjectiveReviewsField;

        /// <remarks/>
        public string TeacherID
        {
            get
            {
                return this.teacherIDField;
            }
            set
            {
                this.teacherIDField = value;
            }
        }

        /// <remarks/>
        public string TeacherName
        {
            get
            {
                return this.teacherNameField;
            }
            set
            {
                this.teacherNameField = value;
            }
        }

        /// <remarks/>
        public EnumEvaluateType EvaluateType
        {
            get
            {
                return this.evaluateTypeField;
            }
            set
            {
                this.evaluateTypeField = value;
            }
        }

        /// <remarks/>
        public string ReviewValue
        {
            get
            {
                return this.reviewValueField;
            }
            set
            {
                this.reviewValueField = value;
            }
        }

        /// <remarks/>
        public string SubjectiveReviews
        {
            get
            {
                return this.subjectiveReviewsField;
            }
            set
            {
                this.subjectiveReviewsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public enum EnumEvaluateType
    {

        /// <remarks/>
        Hierarchy,

        /// <remarks/>
        Score,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class StudentWorkFile
    {

        private string fileIDField;

        private string fileNameField;

        private string fileExtField;

        private string contentTypeField;

        private double sizeField;

        private long offSetField;

        private byte[] dataField;

        /// <remarks/>
        public string FileID
        {
            get
            {
                return this.fileIDField;
            }
            set
            {
                this.fileIDField = value;
            }
        }

        /// <remarks/>
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        public string FileExt
        {
            get
            {
                return this.fileExtField;
            }
            set
            {
                this.fileExtField = value;
            }
        }

        /// <remarks/>
        public string ContentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }

        /// <remarks/>
        public double Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        public long OffSet
        {
            get
            {
                return this.offSetField;
            }
            set
            {
                this.offSetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StudentWorkTeaUpload))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class StudentWork
    {

        private string workIDField;

        private string workNameField;

        private string gradeIDField;

        private string classIDField;

        private EnumWorkStatus statusField;

        private string catalogIDField;

        private string catalogNameField;

        private string checkCodeField;

        private EnumWorkType typeField;

        private Student studentField;

        private System.DateTime timeField;

        private string descriptionField;

        /// <remarks/>
        public string WorkID
        {
            get
            {
                return this.workIDField;
            }
            set
            {
                this.workIDField = value;
            }
        }

        /// <remarks/>
        public string WorkName
        {
            get
            {
                return this.workNameField;
            }
            set
            {
                this.workNameField = value;
            }
        }

        /// <remarks/>
        public string GradeID
        {
            get
            {
                return this.gradeIDField;
            }
            set
            {
                this.gradeIDField = value;
            }
        }

        /// <remarks/>
        public string ClassID
        {
            get
            {
                return this.classIDField;
            }
            set
            {
                this.classIDField = value;
            }
        }

        /// <remarks/>
        public EnumWorkStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string CatalogID
        {
            get
            {
                return this.catalogIDField;
            }
            set
            {
                this.catalogIDField = value;
            }
        }

        /// <remarks/>
        public string CatalogName
        {
            get
            {
                return this.catalogNameField;
            }
            set
            {
                this.catalogNameField = value;
            }
        }

        /// <remarks/>
        public string CheckCode
        {
            get
            {
                return this.checkCodeField;
            }
            set
            {
                this.checkCodeField = value;
            }
        }

        /// <remarks/>
        public EnumWorkType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public Student Student
        {
            get
            {
                return this.studentField;
            }
            set
            {
                this.studentField = value;
            }
        }

        /// <remarks/>
        public System.DateTime Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public enum EnumWorkStatus
    {

        /// <remarks/>
        None = 1,

        /// <remarks/>
        Submit = 2,

        /// <remarks/>
        Recive = 4,

        /// <remarks/>
        Review = 8,

        /// <remarks/>
        Upload = 16,

        /// <remarks/>
        Release = 32,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public enum EnumWorkType
    {

        /// <remarks/>
        Public,

        /// <remarks/>
        Protected,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class Student
    {

        private string studentIDField;

        private string studentCodeField;

        private string studentNameField;

        /// <remarks/>
        public string StudentID
        {
            get
            {
                return this.studentIDField;
            }
            set
            {
                this.studentIDField = value;
            }
        }

        /// <remarks/>
        public string StudentCode
        {
            get
            {
                return this.studentCodeField;
            }
            set
            {
                this.studentCodeField = value;
            }
        }

        /// <remarks/>
        public string StudentName
        {
            get
            {
                return this.studentNameField;
            }
            set
            {
                this.studentNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class StudentWorkTeaUpload : StudentWork
    {

        private StudentWorkFile filesField;

        private TeacherReview reviewField;

        /// <remarks/>
        public StudentWorkFile Files
        {
            get
            {
                return this.filesField;
            }
            set
            {
                this.filesField = value;
            }
        }

        /// <remarks/>
        public TeacherReview Review
        {
            get
            {
                return this.reviewField;
            }
            set
            {
                this.reviewField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class Class
    {

        private string classIDField;

        private string classCodeField;

        private string classNameField;

        private int orderNOField;

        private Student[] studentsField;

        /// <remarks/>
        public string ClassID
        {
            get
            {
                return this.classIDField;
            }
            set
            {
                this.classIDField = value;
            }
        }

        /// <remarks/>
        public string ClassCode
        {
            get
            {
                return this.classCodeField;
            }
            set
            {
                this.classCodeField = value;
            }
        }

        /// <remarks/>
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
            }
        }

        /// <remarks/>
        public int OrderNO
        {
            get
            {
                return this.orderNOField;
            }
            set
            {
                this.orderNOField = value;
            }
        }

        /// <remarks/>
        public Student[] Students
        {
            get
            {
                return this.studentsField;
            }
            set
            {
                this.studentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class KnowledgePoint
    {

        private string pointIDField;

        private string pointCodeField;

        private string pointNameField;

        private string descriptionField;

        private int orderNOField;

        /// <remarks/>
        public string PointID
        {
            get
            {
                return this.pointIDField;
            }
            set
            {
                this.pointIDField = value;
            }
        }

        /// <remarks/>
        public string PointCode
        {
            get
            {
                return this.pointCodeField;
            }
            set
            {
                this.pointCodeField = value;
            }
        }

        /// <remarks/>
        public string PointName
        {
            get
            {
                return this.pointNameField;
            }
            set
            {
                this.pointNameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public int OrderNO
        {
            get
            {
                return this.orderNOField;
            }
            set
            {
                this.orderNOField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class Catalog
    {

        private string catalogIDField;

        private string catalogCodeField;

        private string catalogNameField;

        private string typeNameField;

        private int orderNOField;

        private KnowledgePoint[] pointsField;

        /// <remarks/>
        public string CatalogID
        {
            get
            {
                return this.catalogIDField;
            }
            set
            {
                this.catalogIDField = value;
            }
        }

        /// <remarks/>
        public string CatalogCode
        {
            get
            {
                return this.catalogCodeField;
            }
            set
            {
                this.catalogCodeField = value;
            }
        }

        /// <remarks/>
        public string CatalogName
        {
            get
            {
                return this.catalogNameField;
            }
            set
            {
                this.catalogNameField = value;
            }
        }

        /// <remarks/>
        public string TypeName
        {
            get
            {
                return this.typeNameField;
            }
            set
            {
                this.typeNameField = value;
            }
        }

        /// <remarks/>
        public int OrderNO
        {
            get
            {
                return this.orderNOField;
            }
            set
            {
                this.orderNOField = value;
            }
        }

        /// <remarks/>
        public KnowledgePoint[] Points
        {
            get
            {
                return this.pointsField;
            }
            set
            {
                this.pointsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class EvaluateItem
    {

        private string itemIDField;

        private string itemNameField;

        private string itemValueField;

        /// <remarks/>
        public string ItemID
        {
            get
            {
                return this.itemIDField;
            }
            set
            {
                this.itemIDField = value;
            }
        }

        /// <remarks/>
        public string ItemName
        {
            get
            {
                return this.itemNameField;
            }
            set
            {
                this.itemNameField = value;
            }
        }

        /// <remarks/>
        public string ItemValue
        {
            get
            {
                return this.itemValueField;
            }
            set
            {
                this.itemValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class Evaluate
    {

        private string evaluateIDField;

        private string evaluateNameField;

        private EnumEvaluateType typeField;

        private int maxValueField;

        private int minValueField;

        private EvaluateItem[] itemsField;

        /// <remarks/>
        public string EvaluateID
        {
            get
            {
                return this.evaluateIDField;
            }
            set
            {
                this.evaluateIDField = value;
            }
        }

        /// <remarks/>
        public string EvaluateName
        {
            get
            {
                return this.evaluateNameField;
            }
            set
            {
                this.evaluateNameField = value;
            }
        }

        /// <remarks/>
        public EnumEvaluateType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public int MaxValue
        {
            get
            {
                return this.maxValueField;
            }
            set
            {
                this.maxValueField = value;
            }
        }

        /// <remarks/>
        public int MinValue
        {
            get
            {
                return this.minValueField;
            }
            set
            {
                this.minValueField = value;
            }
        }

        /// <remarks/>
        public EvaluateItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class Grade
    {

        private string gradeIDField;

        private string gradeCodeField;

        private string gradeNameField;

        private int orderNOField;

        private Evaluate evaluateField;

        private Catalog[] catalogsField;

        private Class[] classesField;

        /// <remarks/>
        public string GradeID
        {
            get
            {
                return this.gradeIDField;
            }
            set
            {
                this.gradeIDField = value;
            }
        }

        /// <remarks/>
        public string GradeCode
        {
            get
            {
                return this.gradeCodeField;
            }
            set
            {
                this.gradeCodeField = value;
            }
        }

        /// <remarks/>
        public string GradeName
        {
            get
            {
                return this.gradeNameField;
            }
            set
            {
                this.gradeNameField = value;
            }
        }

        /// <remarks/>
        public int OrderNO
        {
            get
            {
                return this.orderNOField;
            }
            set
            {
                this.orderNOField = value;
            }
        }

        /// <remarks/>
        public Evaluate Evaluate
        {
            get
            {
                return this.evaluateField;
            }
            set
            {
                this.evaluateField = value;
            }
        }

        /// <remarks/>
        public Catalog[] Catalogs
        {
            get
            {
                return this.catalogsField;
            }
            set
            {
                this.catalogsField = value;
            }
        }

        /// <remarks/>
        public Class[] Classes
        {
            get
            {
                return this.classesField;
            }
            set
            {
                this.classesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class Teacher
    {

        private string teacherIDField;

        private string teacherCodeField;

        private string teacherNameField;

        private Grade[] gradesField;

        /// <remarks/>
        public string TeacherID
        {
            get
            {
                return this.teacherIDField;
            }
            set
            {
                this.teacherIDField = value;
            }
        }

        /// <remarks/>
        public string TeacherCode
        {
            get
            {
                return this.teacherCodeField;
            }
            set
            {
                this.teacherCodeField = value;
            }
        }

        /// <remarks/>
        public string TeacherName
        {
            get
            {
                return this.teacherNameField;
            }
            set
            {
                this.teacherNameField = value;
            }
        }

        /// <remarks/>
        public Grade[] Grades
        {
            get
            {
                return this.gradesField;
            }
            set
            {
                this.gradesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class School
    {

        private string schoolIDField;

        private string schoolCodeField;

        private string schoolNameField;

        private EnumSchoolType schoolTypeField;

        private Teacher teacherField;

        /// <remarks/>
        public string SchoolID
        {
            get
            {
                return this.schoolIDField;
            }
            set
            {
                this.schoolIDField = value;
            }
        }

        /// <remarks/>
        public string SchoolCode
        {
            get
            {
                return this.schoolCodeField;
            }
            set
            {
                this.schoolCodeField = value;
            }
        }

        /// <remarks/>
        public string SchoolName
        {
            get
            {
                return this.schoolNameField;
            }
            set
            {
                this.schoolNameField = value;
            }
        }

        /// <remarks/>
        public EnumSchoolType SchoolType
        {
            get
            {
                return this.schoolTypeField;
            }
            set
            {
                this.schoolTypeField = value;
            }
        }

        /// <remarks/>
        public Teacher Teacher
        {
            get
            {
                return this.teacherField;
            }
            set
            {
                this.teacherField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public enum EnumSchoolType
    {

        /// <remarks/>
        Nursery,

        /// <remarks/>
        PrimarySchool,

        /// <remarks/>
        JuniorHighSchool,

        /// <remarks/>
        HighSchool,

        /// <remarks/>
        ConsistentSystemSchool,

        /// <remarks/>
        TwoUnit,

        /// <remarks/>
        Bureau,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class TeaSyncData
    {

        private System.DateTime timeField;

        private School schoolField;

        /// <remarks/>
        public System.DateTime Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        public School School
        {
            get
            {
                return this.schoolField;
            }
            set
            {
                this.schoolField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeneralCallResultOfTeaSyncData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class CallResult
    {

        private int resultCodeField;

        private string resultMessageField;

        /// <remarks/>
        public int ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ipower.org/")]
    public partial class GeneralCallResultOfTeaSyncData : CallResult
    {

        private TeaSyncData dataField;

        /// <remarks/>
        public TeaSyncData Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void VerifyUserIdentityCompletedEventHandler(object sender, VerifyUserIdentityCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyUserIdentityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VerifyUserIdentityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CallResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CallResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void DownloadTeaSyncDataCompletedEventHandler(object sender, DownloadTeaSyncDataCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadTeaSyncDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DownloadTeaSyncDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public GeneralCallResultOfTeaSyncData Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((GeneralCallResultOfTeaSyncData)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void UploadStudentWorksCompletedEventHandler(object sender, UploadStudentWorksCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadStudentWorksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UploadStudentWorksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CallResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CallResult)(this.results[0]));
            }
        }
    }
}