//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.3038。
// 
namespace Yaesoft.iCampus.Poxy
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "DataInterfaceWS_SFITSoap", Namespace = "http://www.yaeosft.net/")]
    internal partial class DataInterfaceWS_SFIT : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback UserAuthorizationVerificationOperationCompleted;

        private CredentialSoapHeader credentialSoapHeaderValueField;

        private System.Threading.SendOrPostCallback SyncAllUnitOperationCompleted;

        private System.Threading.SendOrPostCallback SyncAllTeachersOperationCompleted;

        private System.Threading.SendOrPostCallback SyncAllClassesOperationCompleted;

        private System.Threading.SendOrPostCallback SyncAllStudentsOperationCompleted;

        /// <remarks/>
        public DataInterfaceWS_SFIT()
        {
            this.Url = "http://yaesoft-chk/jwweb_2011/WebService/DataInterfaceWS_SFIT.asmx";
        }

        public CredentialSoapHeader CredentialSoapHeaderValue
        {
            get
            {
                return this.credentialSoapHeaderValueField;
            }
            set
            {
                this.credentialSoapHeaderValueField = value;
            }
        }

        /// <remarks/>
        public event UserAuthorizationVerificationCompletedEventHandler UserAuthorizationVerificationCompleted;

        /// <remarks/>
        public event SyncAllUnitCompletedEventHandler SyncAllUnitCompleted;

        /// <remarks/>
        public event SyncAllTeachersCompletedEventHandler SyncAllTeachersCompleted;

        /// <remarks/>
        public event SyncAllClassesCompletedEventHandler SyncAllClassesCompleted;

        /// <remarks/>
        public event SyncAllStudentsCompletedEventHandler SyncAllStudentsCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yaeosft.net/UserAuthorizationVerification", RequestNamespace = "http://www.yaeosft.net/", ResponseNamespace = "http://www.yaeosft.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UserAuthorizationVerification(int type, string account, string password, out string err)
        {
            object[] results = this.Invoke("UserAuthorizationVerification", new object[] {
                    type,
                    account,
                    password});
            err = ((string)(results[1]));
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUserAuthorizationVerification(int type, string account, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UserAuthorizationVerification", new object[] {
                    type,
                    account,
                    password}, callback, asyncState);
        }

        /// <remarks/>
        public string EndUserAuthorizationVerification(System.IAsyncResult asyncResult, out string err)
        {
            object[] results = this.EndInvoke(asyncResult);
            err = ((string)(results[1]));
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void UserAuthorizationVerificationAsync(int type, string account, string password)
        {
            this.UserAuthorizationVerificationAsync(type, account, password, null);
        }

        /// <remarks/>
        public void UserAuthorizationVerificationAsync(int type, string account, string password, object userState)
        {
            if ((this.UserAuthorizationVerificationOperationCompleted == null))
            {
                this.UserAuthorizationVerificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAuthorizationVerificationOperationCompleted);
            }
            this.InvokeAsync("UserAuthorizationVerification", new object[] {
                    type,
                    account,
                    password}, this.UserAuthorizationVerificationOperationCompleted, userState);
        }

        private void OnUserAuthorizationVerificationOperationCompleted(object arg)
        {
            if ((this.UserAuthorizationVerificationCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAuthorizationVerificationCompleted(this, new UserAuthorizationVerificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yaeosft.net/SyncAllUnit", RequestNamespace = "http://www.yaeosft.net/", ResponseNamespace = "http://www.yaeosft.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SyncAllUnit(out string err)
        {
            object[] results = this.Invoke("SyncAllUnit", new object[0]);
            err = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSyncAllUnit(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SyncAllUnit", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndSyncAllUnit(System.IAsyncResult asyncResult, out string err)
        {
            object[] results = this.EndInvoke(asyncResult);
            err = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void SyncAllUnitAsync()
        {
            this.SyncAllUnitAsync(null);
        }

        /// <remarks/>
        public void SyncAllUnitAsync(object userState)
        {
            if ((this.SyncAllUnitOperationCompleted == null))
            {
                this.SyncAllUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncAllUnitOperationCompleted);
            }
            this.InvokeAsync("SyncAllUnit", new object[0], this.SyncAllUnitOperationCompleted, userState);
        }

        private void OnSyncAllUnitOperationCompleted(object arg)
        {
            if ((this.SyncAllUnitCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncAllUnitCompleted(this, new SyncAllUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yaeosft.net/SyncAllTeachers", RequestNamespace = "http://www.yaeosft.net/", ResponseNamespace = "http://www.yaeosft.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SyncAllTeachers(string unitName, out string err)
        {
            object[] results = this.Invoke("SyncAllTeachers", new object[] {
                    unitName});
            err = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSyncAllTeachers(string unitName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SyncAllTeachers", new object[] {
                    unitName}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndSyncAllTeachers(System.IAsyncResult asyncResult, out string err)
        {
            object[] results = this.EndInvoke(asyncResult);
            err = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void SyncAllTeachersAsync(string unitName)
        {
            this.SyncAllTeachersAsync(unitName, null);
        }

        /// <remarks/>
        public void SyncAllTeachersAsync(string unitName, object userState)
        {
            if ((this.SyncAllTeachersOperationCompleted == null))
            {
                this.SyncAllTeachersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncAllTeachersOperationCompleted);
            }
            this.InvokeAsync("SyncAllTeachers", new object[] {
                    unitName}, this.SyncAllTeachersOperationCompleted, userState);
        }

        private void OnSyncAllTeachersOperationCompleted(object arg)
        {
            if ((this.SyncAllTeachersCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncAllTeachersCompleted(this, new SyncAllTeachersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yaeosft.net/SyncAllClasses", RequestNamespace = "http://www.yaeosft.net/", ResponseNamespace = "http://www.yaeosft.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SyncAllClasses(string unitName, out string err)
        {
            object[] results = this.Invoke("SyncAllClasses", new object[] {
                    unitName});
            err = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSyncAllClasses(string unitName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SyncAllClasses", new object[] {
                    unitName}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndSyncAllClasses(System.IAsyncResult asyncResult, out string err)
        {
            object[] results = this.EndInvoke(asyncResult);
            err = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void SyncAllClassesAsync(string unitName)
        {
            this.SyncAllClassesAsync(unitName, null);
        }

        /// <remarks/>
        public void SyncAllClassesAsync(string unitName, object userState)
        {
            if ((this.SyncAllClassesOperationCompleted == null))
            {
                this.SyncAllClassesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncAllClassesOperationCompleted);
            }
            this.InvokeAsync("SyncAllClasses", new object[] {
                    unitName}, this.SyncAllClassesOperationCompleted, userState);
        }

        private void OnSyncAllClassesOperationCompleted(object arg)
        {
            if ((this.SyncAllClassesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncAllClassesCompleted(this, new SyncAllClassesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredentialSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.yaeosft.net/SyncAllStudents", RequestNamespace = "http://www.yaeosft.net/", ResponseNamespace = "http://www.yaeosft.net/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SyncAllStudents(string unitName, string joinYear, string className, out string err)
        {
            object[] results = this.Invoke("SyncAllStudents", new object[] {
                    unitName,
                    joinYear,
                    className});
            err = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSyncAllStudents(string unitName, string joinYear, string className, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SyncAllStudents", new object[] {
                    unitName,
                    joinYear,
                    className}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndSyncAllStudents(System.IAsyncResult asyncResult, out string err)
        {
            object[] results = this.EndInvoke(asyncResult);
            err = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void SyncAllStudentsAsync(string unitName, string joinYear, string className)
        {
            this.SyncAllStudentsAsync(unitName, joinYear, className, null);
        }

        /// <remarks/>
        public void SyncAllStudentsAsync(string unitName, string joinYear, string className, object userState)
        {
            if ((this.SyncAllStudentsOperationCompleted == null))
            {
                this.SyncAllStudentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncAllStudentsOperationCompleted);
            }
            this.InvokeAsync("SyncAllStudents", new object[] {
                    unitName,
                    joinYear,
                    className}, this.SyncAllStudentsOperationCompleted, userState);
        }

        private void OnSyncAllStudentsOperationCompleted(object arg)
        {
            if ((this.SyncAllStudentsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncAllStudentsCompleted(this, new SyncAllStudentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.yaeosft.net/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yaeosft.net/", IsNullable = false)]
    internal partial class CredentialSoapHeader : System.Web.Services.Protocols.SoapHeader
    {

        private string userIDField;

        private string userPassField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string UserPass
        {
            get
            {
                return this.userPassField;
            }
            set
            {
                this.userPassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void UserAuthorizationVerificationCompletedEventHandler(object sender, UserAuthorizationVerificationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class UserAuthorizationVerificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UserAuthorizationVerificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }

        /// <remarks/>
        public string err
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void SyncAllUnitCompletedEventHandler(object sender, SyncAllUnitCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class SyncAllUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SyncAllUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }

        /// <remarks/>
        public string err
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void SyncAllTeachersCompletedEventHandler(object sender, SyncAllTeachersCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class SyncAllTeachersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SyncAllTeachersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }

        /// <remarks/>
        public string err
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void SyncAllClassesCompletedEventHandler(object sender, SyncAllClassesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class SyncAllClassesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SyncAllClassesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }

        /// <remarks/>
        public string err
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    internal delegate void SyncAllStudentsCompletedEventHandler(object sender, SyncAllStudentsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    internal partial class SyncAllStudentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SyncAllStudentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }

        /// <remarks/>
        public string err
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}