//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaesoft.SFIT.Web {
    
    
    public partial class UCStudentWork {
        
        /// <summary>
        /// lbWorkName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbWorkName;
        
        /// <summary>
        /// txtWorkName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtWorkName;
        
        /// <summary>
        /// lbWorkType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbWorkType;
        
        /// <summary>
        /// ddlWorkType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.DropDownListEx ddlWorkType;
        
        /// <summary>
        /// lbWorkStatus 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbWorkStatus;
        
        /// <summary>
        /// chkWorkStatus 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.CheckBoxListEx chkWorkStatus;
        
        /// <summary>
        /// panelCheckCode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panelCheckCode;
        
        /// <summary>
        /// lbCheckCode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbCheckCode;
        
        /// <summary>
        /// txtCheckCode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtCheckCode;
        
        /// <summary>
        /// lbWorkDescription 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbWorkDescription;
        
        /// <summary>
        /// txtWorkDescription 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtWorkDescription;
        
        /// <summary>
        /// lbSchoolName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbSchoolName;
        
        /// <summary>
        /// txtSchoolName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtSchoolName;
        
        /// <summary>
        /// lbGradeName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbGradeName;
        
        /// <summary>
        /// txtGradeName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtGradeName;
        
        /// <summary>
        /// lbClassName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbClassName;
        
        /// <summary>
        /// txtClassName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtClassName;
        
        /// <summary>
        /// lbStudentName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbStudentName;
        
        /// <summary>
        /// txtStudentName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtStudentName;
        
        /// <summary>
        /// lbCatalogName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbCatalogName;
        
        /// <summary>
        /// txtCatalogName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtCatalogName;
    }
}
