//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.3038。
// 
namespace Yaesoft.Furong.Proxy.TeaProxy
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "LoginServiceSoap", Namespace = "http://webservice.furongedu.com/LoginService/LoginService")]
    public partial class TeaLoginService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private AuthHeader authHeaderValueField;

        private System.Threading.SendOrPostCallback HaveUserOperationCompleted;

        private System.Threading.SendOrPostCallback VerifyUserOperationCompleted;

        private System.Threading.SendOrPostCallback GetUserInfoOperationCompleted;

        private System.Threading.SendOrPostCallback GetUserInfoAtLeiXinOperationCompleted;

        private System.Threading.SendOrPostCallback GetUnitUserInfoOperationCompleted;

        private System.Threading.SendOrPostCallback GetUserInfo2OperationCompleted;

        private System.Threading.SendOrPostCallback GetUserPassWordOperationCompleted;

        private System.Threading.SendOrPostCallback GetUnitInfoOperationCompleted;

        private System.Threading.SendOrPostCallback GetUnitAllUserInfoOperationCompleted;

        private System.Threading.SendOrPostCallback SearchUserOperationCompleted;

        /// <remarks/>
        public TeaLoginService()
        {
            this.Url = "http://webservice.furongedu.com/LoginService/Loginservice.asmx";
        }
        /// <summary>
        /// 
        /// </summary>
        public AuthHeader AuthHeaderValue
        {
            get
            {
                return this.authHeaderValueField;
            }
            set
            {
                this.authHeaderValueField = value;
            }
        }

        /// <remarks/>
        public event HaveUserCompletedEventHandler HaveUserCompleted;

        /// <remarks/>
        public event VerifyUserCompletedEventHandler VerifyUserCompleted;

        /// <remarks/>
        public event GetUserInfoCompletedEventHandler GetUserInfoCompleted;

        /// <remarks/>
        public event GetUserInfoAtLeiXinCompletedEventHandler GetUserInfoAtLeiXinCompleted;

        /// <remarks/>
        public event GetUnitUserInfoCompletedEventHandler GetUnitUserInfoCompleted;

        /// <remarks/>
        public event GetUserInfo2CompletedEventHandler GetUserInfo2Completed;

        /// <remarks/>
        public event GetUserPassWordCompletedEventHandler GetUserPassWordCompleted;

        /// <remarks/>
        public event GetUnitInfoCompletedEventHandler GetUnitInfoCompleted;

        /// <remarks/>
        public event GetUnitAllUserInfoCompletedEventHandler GetUnitAllUserInfoCompleted;

        /// <remarks/>
        public event SearchUserCompletedEventHandler SearchUserCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.furongedu.com/LoginService/LoginService/HaveUser", RequestNamespace = "http://webservice.furongedu.com/LoginService/LoginService", ResponseNamespace = "http://webservice.furongedu.com/LoginService/LoginService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HaveUser(string UserName)
        {
            object[] results = this.Invoke("HaveUser", new object[] {
                    UserName});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginHaveUser(string UserName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("HaveUser", new object[] {
                    UserName}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndHaveUser(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void HaveUserAsync(string UserName)
        {
            this.HaveUserAsync(UserName, null);
        }

        /// <remarks/>
        public void HaveUserAsync(string UserName, object userState)
        {
            if ((this.HaveUserOperationCompleted == null))
            {
                this.HaveUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHaveUserOperationCompleted);
            }
            this.InvokeAsync("HaveUser", new object[] {
                    UserName}, this.HaveUserOperationCompleted, userState);
        }

        private void OnHaveUserOperationCompleted(object arg)
        {
            if ((this.HaveUserCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HaveUserCompleted(this, new HaveUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.furongedu.com/LoginService/LoginService/VerifyUser", RequestNamespace = "http://webservice.furongedu.com/LoginService/LoginService", ResponseNamespace = "http://webservice.furongedu.com/LoginService/LoginService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyUser(string UserName, string PassWord)
        {
            object[] results = this.Invoke("VerifyUser", new object[] {
                    UserName,
                    PassWord});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginVerifyUser(string UserName, string PassWord, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("VerifyUser", new object[] {
                    UserName,
                    PassWord}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndVerifyUser(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void VerifyUserAsync(string UserName, string PassWord)
        {
            this.VerifyUserAsync(UserName, PassWord, null);
        }

        /// <remarks/>
        public void VerifyUserAsync(string UserName, string PassWord, object userState)
        {
            if ((this.VerifyUserOperationCompleted == null))
            {
                this.VerifyUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyUserOperationCompleted);
            }
            this.InvokeAsync("VerifyUser", new object[] {
                    UserName,
                    PassWord}, this.VerifyUserOperationCompleted, userState);
        }

        private void OnVerifyUserOperationCompleted(object arg)
        {
            if ((this.VerifyUserCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyUserCompleted(this, new VerifyUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.furongedu.com/LoginService/LoginService/GetUserInfo", RequestNamespace = "http://webservice.furongedu.com/LoginService/LoginService", ResponseNamespace = "http://webservice.furongedu.com/LoginService/LoginService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserInfo(string UserName, string PassWord)
        {
            object[] results = this.Invoke("GetUserInfo", new object[] {
                    UserName,
                    PassWord});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetUserInfo(string UserName, string PassWord, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetUserInfo", new object[] {
                    UserName,
                    PassWord}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetUserInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetUserInfoAsync(string UserName, string PassWord)
        {
            this.GetUserInfoAsync(UserName, PassWord, null);
        }

        /// <remarks/>
        public void GetUserInfoAsync(string UserName, string PassWord, object userState)
        {
            if ((this.GetUserInfoOperationCompleted == null))
            {
                this.GetUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetUserInfo", new object[] {
                    UserName,
                    PassWord}, this.GetUserInfoOperationCompleted, userState);
        }

        private void OnGetUserInfoOperationCompleted(object arg)
        {
            if ((this.GetUserInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoCompleted(this, new GetUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.furongedu.com/LoginService/LoginService/GetUserInfoAtLeiXin", RequestNamespace = "http://webservice.furongedu.com/LoginService/LoginService", ResponseNamespace = "http://webservice.furongedu.com/LoginService/LoginService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserInfoAtLeiXin(string LeiXinName)
        {
            object[] results = this.Invoke("GetUserInfoAtLeiXin", new object[] {
                    LeiXinName});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetUserInfoAtLeiXin(string LeiXinName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetUserInfoAtLeiXin", new object[] {
                    LeiXinName}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetUserInfoAtLeiXin(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetUserInfoAtLeiXinAsync(string LeiXinName)
        {
            this.GetUserInfoAtLeiXinAsync(LeiXinName, null);
        }

        /// <remarks/>
        public void GetUserInfoAtLeiXinAsync(string LeiXinName, object userState)
        {
            if ((this.GetUserInfoAtLeiXinOperationCompleted == null))
            {
                this.GetUserInfoAtLeiXinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoAtLeiXinOperationCompleted);
            }
            this.InvokeAsync("GetUserInfoAtLeiXin", new object[] {
                    LeiXinName}, this.GetUserInfoAtLeiXinOperationCompleted, userState);
        }

        private void OnGetUserInfoAtLeiXinOperationCompleted(object arg)
        {
            if ((this.GetUserInfoAtLeiXinCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoAtLeiXinCompleted(this, new GetUserInfoAtLeiXinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.furongedu.com/LoginService/LoginService/GetUnitUserInfo", RequestNamespace = "http://webservice.furongedu.com/LoginService/LoginService", ResponseNamespace = "http://webservice.furongedu.com/LoginService/LoginService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUnitUserInfo(string UserName, string PassWord)
        {
            object[] results = this.Invoke("GetUnitUserInfo", new object[] {
                    UserName,
                    PassWord});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetUnitUserInfo(string UserName, string PassWord, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetUnitUserInfo", new object[] {
                    UserName,
                    PassWord}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetUnitUserInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetUnitUserInfoAsync(string UserName, string PassWord)
        {
            this.GetUnitUserInfoAsync(UserName, PassWord, null);
        }

        /// <remarks/>
        public void GetUnitUserInfoAsync(string UserName, string PassWord, object userState)
        {
            if ((this.GetUnitUserInfoOperationCompleted == null))
            {
                this.GetUnitUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetUnitUserInfo", new object[] {
                    UserName,
                    PassWord}, this.GetUnitUserInfoOperationCompleted, userState);
        }

        private void OnGetUnitUserInfoOperationCompleted(object arg)
        {
            if ((this.GetUnitUserInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitUserInfoCompleted(this, new GetUnitUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.furongedu.com/LoginService/LoginService/GetUserInfo2", RequestNamespace = "http://webservice.furongedu.com/LoginService/LoginService", ResponseNamespace = "http://webservice.furongedu.com/LoginService/LoginService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserInfo2(string UserName)
        {
            object[] results = this.Invoke("GetUserInfo2", new object[] {
                    UserName});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetUserInfo2(string UserName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetUserInfo2", new object[] {
                    UserName}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetUserInfo2(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetUserInfo2Async(string UserName)
        {
            this.GetUserInfo2Async(UserName, null);
        }

        /// <remarks/>
        public void GetUserInfo2Async(string UserName, object userState)
        {
            if ((this.GetUserInfo2OperationCompleted == null))
            {
                this.GetUserInfo2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfo2OperationCompleted);
            }
            this.InvokeAsync("GetUserInfo2", new object[] {
                    UserName}, this.GetUserInfo2OperationCompleted, userState);
        }

        private void OnGetUserInfo2OperationCompleted(object arg)
        {
            if ((this.GetUserInfo2Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfo2Completed(this, new GetUserInfo2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.furongedu.com/LoginService/LoginService/GetUserPassWord", RequestNamespace = "http://webservice.furongedu.com/LoginService/LoginService", ResponseNamespace = "http://webservice.furongedu.com/LoginService/LoginService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserPassWord(string UserName, string Tel)
        {
            object[] results = this.Invoke("GetUserPassWord", new object[] {
                    UserName,
                    Tel});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetUserPassWord(string UserName, string Tel, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetUserPassWord", new object[] {
                    UserName,
                    Tel}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetUserPassWord(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetUserPassWordAsync(string UserName, string Tel)
        {
            this.GetUserPassWordAsync(UserName, Tel, null);
        }

        /// <remarks/>
        public void GetUserPassWordAsync(string UserName, string Tel, object userState)
        {
            if ((this.GetUserPassWordOperationCompleted == null))
            {
                this.GetUserPassWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPassWordOperationCompleted);
            }
            this.InvokeAsync("GetUserPassWord", new object[] {
                    UserName,
                    Tel}, this.GetUserPassWordOperationCompleted, userState);
        }

        private void OnGetUserPassWordOperationCompleted(object arg)
        {
            if ((this.GetUserPassWordCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPassWordCompleted(this, new GetUserPassWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.furongedu.com/LoginService/LoginService/GetUnitInfo", RequestNamespace = "http://webservice.furongedu.com/LoginService/LoginService", ResponseNamespace = "http://webservice.furongedu.com/LoginService/LoginService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUnitInfo()
        {
            object[] results = this.Invoke("GetUnitInfo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetUnitInfo(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetUnitInfo", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetUnitInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetUnitInfoAsync()
        {
            this.GetUnitInfoAsync(null);
        }

        /// <remarks/>
        public void GetUnitInfoAsync(object userState)
        {
            if ((this.GetUnitInfoOperationCompleted == null))
            {
                this.GetUnitInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitInfoOperationCompleted);
            }
            this.InvokeAsync("GetUnitInfo", new object[0], this.GetUnitInfoOperationCompleted, userState);
        }

        private void OnGetUnitInfoOperationCompleted(object arg)
        {
            if ((this.GetUnitInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitInfoCompleted(this, new GetUnitInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.furongedu.com/LoginService/LoginService/GetUnitAllUserInfo", RequestNamespace = "http://webservice.furongedu.com/LoginService/LoginService", ResponseNamespace = "http://webservice.furongedu.com/LoginService/LoginService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUnitAllUserInfo(string UnitName)
        {
            object[] results = this.Invoke("GetUnitAllUserInfo", new object[] {
                    UnitName});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetUnitAllUserInfo(string UnitName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetUnitAllUserInfo", new object[] {
                    UnitName}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetUnitAllUserInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetUnitAllUserInfoAsync(string UnitName)
        {
            this.GetUnitAllUserInfoAsync(UnitName, null);
        }

        /// <remarks/>
        public void GetUnitAllUserInfoAsync(string UnitName, object userState)
        {
            if ((this.GetUnitAllUserInfoOperationCompleted == null))
            {
                this.GetUnitAllUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitAllUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetUnitAllUserInfo", new object[] {
                    UnitName}, this.GetUnitAllUserInfoOperationCompleted, userState);
        }

        private void OnGetUnitAllUserInfoOperationCompleted(object arg)
        {
            if ((this.GetUnitAllUserInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitAllUserInfoCompleted(this, new GetUnitAllUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.furongedu.com/LoginService/LoginService/SearchUser", RequestNamespace = "http://webservice.furongedu.com/LoginService/LoginService", ResponseNamespace = "http://webservice.furongedu.com/LoginService/LoginService", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SearchUser(string strFieldName, string strKey)
        {
            object[] results = this.Invoke("SearchUser", new object[] {
                    strFieldName,
                    strKey});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSearchUser(string strFieldName, string strKey, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SearchUser", new object[] {
                    strFieldName,
                    strKey}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndSearchUser(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void SearchUserAsync(string strFieldName, string strKey)
        {
            this.SearchUserAsync(strFieldName, strKey, null);
        }

        /// <remarks/>
        public void SearchUserAsync(string strFieldName, string strKey, object userState)
        {
            if ((this.SearchUserOperationCompleted == null))
            {
                this.SearchUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchUserOperationCompleted);
            }
            this.InvokeAsync("SearchUser", new object[] {
                    strFieldName,
                    strKey}, this.SearchUserOperationCompleted, userState);
        }

        private void OnSearchUserOperationCompleted(object arg)
        {
            if ((this.SearchUserCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchUserCompleted(this, new SearchUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservice.furongedu.com/LoginService/LoginService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://webservice.furongedu.com/LoginService/LoginService", IsNullable = false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader
    {

        private string userNameField;

        private string passWordField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string PassWord
        {
            get
            {
                return this.passWordField;
            }
            set
            {
                this.passWordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void HaveUserCompletedEventHandler(object sender, HaveUserCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HaveUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal HaveUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void VerifyUserCompletedEventHandler(object sender, VerifyUserCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VerifyUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetUserInfoCompletedEventHandler(object sender, GetUserInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetUserInfoAtLeiXinCompletedEventHandler(object sender, GetUserInfoAtLeiXinCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoAtLeiXinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetUserInfoAtLeiXinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetUnitUserInfoCompletedEventHandler(object sender, GetUnitUserInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetUnitUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetUserInfo2CompletedEventHandler(object sender, GetUserInfo2CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetUserInfo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetUserPassWordCompletedEventHandler(object sender, GetUserPassWordCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPassWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetUserPassWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetUnitInfoCompletedEventHandler(object sender, GetUnitInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetUnitInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetUnitAllUserInfoCompletedEventHandler(object sender, GetUnitAllUserInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitAllUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetUnitAllUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void SearchUserCompletedEventHandler(object sender, SearchUserCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SearchUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}