//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.3038。
// 
namespace Yaesoft.Furong.Proxy.StuProxy
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "LoginServiceStudentSoap", Namespace = "http://tempuri.org/")]
    public partial class StuLoginService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private AuthHeader authHeaderValueField;

        private System.Threading.SendOrPostCallback GetAllSchoolOperationCompleted;

        private System.Threading.SendOrPostCallback GetTeacherOperationCompleted;

        private System.Threading.SendOrPostCallback GetClassOperationCompleted;

        private System.Threading.SendOrPostCallback GetStudentOperationCompleted;

        private System.Threading.SendOrPostCallback VerifyUserOperationCompleted;

        private System.Threading.SendOrPostCallback VerifyUser2OperationCompleted;

        private System.Threading.SendOrPostCallback VerifyJZOperationCompleted;

        private System.Threading.SendOrPostCallback UpPassWordOperationCompleted;

        /// <remarks/>
        public StuLoginService()
        {
            this.Url = "http://passport.furongedu.com/LoginService/LoginServiceStudent.asmx";
        }
        /// <summary>
        /// 
        /// </summary>
        public AuthHeader AuthHeaderValue
        {
            get
            {
                return this.authHeaderValueField;
            }
            set
            {
                this.authHeaderValueField = value;
            }
        }

        /// <remarks/>
        public event GetAllSchoolCompletedEventHandler GetAllSchoolCompleted;

        /// <remarks/>
        public event GetTeacherCompletedEventHandler GetTeacherCompleted;

        /// <remarks/>
        public event GetClassCompletedEventHandler GetClassCompleted;

        /// <remarks/>
        public event GetStudentCompletedEventHandler GetStudentCompleted;

        /// <remarks/>
        public event VerifyUserCompletedEventHandler VerifyUserCompleted;

        /// <remarks/>
        public event VerifyUser2CompletedEventHandler VerifyUser2Completed;

        /// <remarks/>
        public event VerifyJZCompletedEventHandler VerifyJZCompleted;

        /// <remarks/>
        public event UpPassWordCompletedEventHandler UpPassWordCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllSchool", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllSchool()
        {
            object[] results = this.Invoke("GetAllSchool", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAllSchool(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAllSchool", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndGetAllSchool(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void GetAllSchoolAsync()
        {
            this.GetAllSchoolAsync(null);
        }

        /// <remarks/>
        public void GetAllSchoolAsync(object userState)
        {
            if ((this.GetAllSchoolOperationCompleted == null))
            {
                this.GetAllSchoolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSchoolOperationCompleted);
            }
            this.InvokeAsync("GetAllSchool", new object[0], this.GetAllSchoolOperationCompleted, userState);
        }

        private void OnGetAllSchoolOperationCompleted(object arg)
        {
            if ((this.GetAllSchoolCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSchoolCompleted(this, new GetAllSchoolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTeacher", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTeacher(string dwmc)
        {
            object[] results = this.Invoke("GetTeacher", new object[] {
                    dwmc});
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetTeacher(string dwmc, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetTeacher", new object[] {
                    dwmc}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndGetTeacher(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void GetTeacherAsync(string dwmc)
        {
            this.GetTeacherAsync(dwmc, null);
        }

        /// <remarks/>
        public void GetTeacherAsync(string dwmc, object userState)
        {
            if ((this.GetTeacherOperationCompleted == null))
            {
                this.GetTeacherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeacherOperationCompleted);
            }
            this.InvokeAsync("GetTeacher", new object[] {
                    dwmc}, this.GetTeacherOperationCompleted, userState);
        }

        private void OnGetTeacherOperationCompleted(object arg)
        {
            if ((this.GetTeacherCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeacherCompleted(this, new GetTeacherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClass", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetClass(string dwmc)
        {
            object[] results = this.Invoke("GetClass", new object[] {
                    dwmc});
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetClass(string dwmc, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetClass", new object[] {
                    dwmc}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndGetClass(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void GetClassAsync(string dwmc)
        {
            this.GetClassAsync(dwmc, null);
        }

        /// <remarks/>
        public void GetClassAsync(string dwmc, object userState)
        {
            if ((this.GetClassOperationCompleted == null))
            {
                this.GetClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClassOperationCompleted);
            }
            this.InvokeAsync("GetClass", new object[] {
                    dwmc}, this.GetClassOperationCompleted, userState);
        }

        private void OnGetClassOperationCompleted(object arg)
        {
            if ((this.GetClassCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClassCompleted(this, new GetClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStudent", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetStudent(string dwmc, string rxnf, string bjmc, string xh)
        {
            object[] results = this.Invoke("GetStudent", new object[] {
                    dwmc,
                    rxnf,
                    bjmc,
                    xh});
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetStudent(string dwmc, string rxnf, string bjmc, string xh, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetStudent", new object[] {
                    dwmc,
                    rxnf,
                    bjmc,
                    xh}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndGetStudent(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void GetStudentAsync(string dwmc, string rxnf, string bjmc, string xh)
        {
            this.GetStudentAsync(dwmc, rxnf, bjmc, xh, null);
        }

        /// <remarks/>
        public void GetStudentAsync(string dwmc, string rxnf, string bjmc, string xh, object userState)
        {
            if ((this.GetStudentOperationCompleted == null))
            {
                this.GetStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentOperationCompleted);
            }
            this.InvokeAsync("GetStudent", new object[] {
                    dwmc,
                    rxnf,
                    bjmc,
                    xh}, this.GetStudentOperationCompleted, userState);
        }

        private void OnGetStudentOperationCompleted(object arg)
        {
            if ((this.GetStudentCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentCompleted(this, new GetStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyUser", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable VerifyUser(string account, string passWord)
        {
            object[] results = this.Invoke("VerifyUser", new object[] {
                    account,
                    passWord});
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginVerifyUser(string account, string passWord, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("VerifyUser", new object[] {
                    account,
                    passWord}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndVerifyUser(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void VerifyUserAsync(string account, string passWord)
        {
            this.VerifyUserAsync(account, passWord, null);
        }

        /// <remarks/>
        public void VerifyUserAsync(string account, string passWord, object userState)
        {
            if ((this.VerifyUserOperationCompleted == null))
            {
                this.VerifyUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyUserOperationCompleted);
            }
            this.InvokeAsync("VerifyUser", new object[] {
                    account,
                    passWord}, this.VerifyUserOperationCompleted, userState);
        }

        private void OnVerifyUserOperationCompleted(object arg)
        {
            if ((this.VerifyUserCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyUserCompleted(this, new VerifyUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyUser2", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable VerifyUser2(string account, string passWord)
        {
            object[] results = this.Invoke("VerifyUser2", new object[] {
                    account,
                    passWord});
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginVerifyUser2(string account, string passWord, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("VerifyUser2", new object[] {
                    account,
                    passWord}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndVerifyUser2(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void VerifyUser2Async(string account, string passWord)
        {
            this.VerifyUser2Async(account, passWord, null);
        }

        /// <remarks/>
        public void VerifyUser2Async(string account, string passWord, object userState)
        {
            if ((this.VerifyUser2OperationCompleted == null))
            {
                this.VerifyUser2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyUser2OperationCompleted);
            }
            this.InvokeAsync("VerifyUser2", new object[] {
                    account,
                    passWord}, this.VerifyUser2OperationCompleted, userState);
        }

        private void OnVerifyUser2OperationCompleted(object arg)
        {
            if ((this.VerifyUser2Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyUser2Completed(this, new VerifyUser2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyJZ", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable VerifyJZ(string account, string passWord)
        {
            object[] results = this.Invoke("VerifyJZ", new object[] {
                    account,
                    passWord});
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginVerifyJZ(string account, string passWord, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("VerifyJZ", new object[] {
                    account,
                    passWord}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataTable EndVerifyJZ(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }

        /// <remarks/>
        public void VerifyJZAsync(string account, string passWord)
        {
            this.VerifyJZAsync(account, passWord, null);
        }

        /// <remarks/>
        public void VerifyJZAsync(string account, string passWord, object userState)
        {
            if ((this.VerifyJZOperationCompleted == null))
            {
                this.VerifyJZOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyJZOperationCompleted);
            }
            this.InvokeAsync("VerifyJZ", new object[] {
                    account,
                    passWord}, this.VerifyJZOperationCompleted, userState);
        }

        private void OnVerifyJZOperationCompleted(object arg)
        {
            if ((this.VerifyJZCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyJZCompleted(this, new VerifyJZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpPassWord", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpPassWord(string account, string oldPassWord, string newPassWord, string xsorjz)
        {
            object[] results = this.Invoke("UpPassWord", new object[] {
                    account,
                    oldPassWord,
                    newPassWord,
                    xsorjz});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpPassWord(string account, string oldPassWord, string newPassWord, string xsorjz, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpPassWord", new object[] {
                    account,
                    oldPassWord,
                    newPassWord,
                    xsorjz}, callback, asyncState);
        }

        /// <remarks/>
        public int EndUpPassWord(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void UpPassWordAsync(string account, string oldPassWord, string newPassWord, string xsorjz)
        {
            this.UpPassWordAsync(account, oldPassWord, newPassWord, xsorjz, null);
        }

        /// <remarks/>
        public void UpPassWordAsync(string account, string oldPassWord, string newPassWord, string xsorjz, object userState)
        {
            if ((this.UpPassWordOperationCompleted == null))
            {
                this.UpPassWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpPassWordOperationCompleted);
            }
            this.InvokeAsync("UpPassWord", new object[] {
                    account,
                    oldPassWord,
                    newPassWord,
                    xsorjz}, this.UpPassWordOperationCompleted, userState);
        }

        private void OnUpPassWordOperationCompleted(object arg)
        {
            if ((this.UpPassWordCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpPassWordCompleted(this, new UpPassWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/", IsNullable = false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader
    {

        private string userNameField;

        private string passWordField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string PassWord
        {
            get
            {
                return this.passWordField;
            }
            set
            {
                this.passWordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetAllSchoolCompletedEventHandler(object sender, GetAllSchoolCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSchoolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllSchoolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetTeacherCompletedEventHandler(object sender, GetTeacherCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeacherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetTeacherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetClassCompletedEventHandler(object sender, GetClassCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetStudentCompletedEventHandler(object sender, GetStudentCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void VerifyUserCompletedEventHandler(object sender, VerifyUserCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VerifyUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void VerifyUser2CompletedEventHandler(object sender, VerifyUser2CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyUser2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VerifyUser2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void VerifyJZCompletedEventHandler(object sender, VerifyJZCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyJZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VerifyJZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataTable Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void UpPassWordCompletedEventHandler(object sender, UpPassWordCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpPassWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpPassWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}